checker='time_travel' # One of: time_travel, minkpp

[model]
repo='allenai/OLMo-7B' # One of: AntonV/mamba2-{model_size}-hf, allenai/OLMo-{model_size}, facebook/opt-{model_size}
model_name='OLMo'
model_size='7b'
cache_dir='models'

[dataset]
cache_dir='datasets'

[[dataset.test]]
dataset_name='snli'
dataset_split='test'

[[dataset.test]]
dataset_name='mnli'
dataset_split='validation_matched'

[[dataset.test]]  
dataset_name='scitail'
dataset_split='test'

[[dataset.test]]  
dataset_name='wnli'
dataset_split='train'

[[dataset.test]]  
dataset_name='rte'
dataset_split='train'

[[dataset.test]]  
dataset_name='paws'
dataset_split='test'

[[dataset.test]]  
dataset_name='hans'
dataset_split='validation'

[[dataset.test]]  
dataset_name='anli'
dataset_split='test_r3'
